/* ---------- rendering ---------- */
function renderSideContent(side,content,displayMode="standard"){if(content&&typeof content==="object"&&content.calendarDate){const cal=document.createElement("div");cal.className="calendar-date";const num=document.createElement("div");num.className="calendar-date-number";num.textContent=content.calendarDate;cal.appendChild(num);side.appendChild(cal);return}if(content&&typeof content==="object"&&(content.icons||content.imageSrc)){const w=document.createElement("div");w.className="question-stack";if(content.imageSrc){const img=document.createElement("img");img.className="question-image";img.src=content.imageSrc;img.alt=content.imageName||"問題画像";w.appendChild(img)}if(content.icons){const icons=document.createElement("div");icons.className="question-icons";icons.textContent=content.icons.join("  ");w.appendChild(icons)}const num=document.createElement("div");num.className="question-number";num.textContent=content.number??"";w.appendChild(num);side.appendChild(w);return}if(content&&typeof content==="object"&&content.readings){const b=document.createElement("div");b.className="answer-block";const showReadings=displayMode!=="notation",showNotation=displayMode!=="reading";if(showReadings)content.readings.forEach(r=>{const d=document.createElement("div");d.className="answer-reading";d.textContent=r;b.appendChild(d)});if(showNotation){const n=document.createElement("div");n.className="answer-notation";n.textContent=content.notation??"";b.appendChild(n)}side.appendChild(b);requestAnimationFrame(()=>fitBlock(side,b));return}const d=document.createElement("div");d.className="flash-text";d.textContent=content??"";side.appendChild(d)}
function currentTeacherDisplayMode(){return $("#scriptMode")?.value||"standard"}
function currentLearnerDisplayMode(){return $("#learnerScript")?.value||"standard"}
function displayModeOptions(english=false){const structured=(preset==="counters"||preset==="time"||(preset==="custom"&&customKind==="counter"));if(!structured)return [["standard",english?"Standard":"標準"]];return english?[["readingNotation","Reading + notation"],["reading","Reading only"],["notation","Notation only"]]:[["readingNotation","読み＋表記"],["reading","読みのみ"],["notation","表記のみ"]]}
function refreshDisplayModeSelects(){const keep=$("#scriptMode")?.value;fillSelect($("#scriptMode"),displayModeOptions(false),displayModeOptions(false).some(x=>x[0]===keep)?keep:displayModeOptions(false)[0][0]);const lkeep=$("#learnerScript")?.value;fillSelect($("#learnerScript"),displayModeOptions(true),displayModeOptions(true).some(x=>x[0]===lkeep)?lkeep:displayModeOptions(true)[0][0])}
const opticalCanvas=document.createElement("canvas");const opticalCtx=opticalCanvas.getContext("2d");
function opticalTextShift(el){if(!el||!opticalCtx)return 0;const text=(el.textContent||"").trim();if(!text)return 0;const cs=getComputedStyle(el);const px=parseFloat(cs.fontSize)||16;opticalCtx.font=`${cs.fontStyle||"normal"} ${cs.fontWeight||400} ${px}px ${cs.fontFamily||"sans-serif"}`;const m=opticalCtx.measureText(text);if(!Number.isFinite(m.actualBoundingBoxAscent)||!Number.isFinite(m.actualBoundingBoxDescent))return 0;const fa=Number.isFinite(m.fontBoundingBoxAscent)?m.fontBoundingBoxAscent:px*.9;const fd=Number.isFinite(m.fontBoundingBoxDescent)?m.fontBoundingBoxDescent:px*.22;const inkCenter=(m.actualBoundingBoxDescent-m.actualBoundingBoxAscent)/2;const fontCenter=(fd-fa)/2;return fontCenter-inkCenter}
function applyOpticalTextCenter(root){if(!root)return;root.querySelectorAll(".flash-text,.question-icons,.question-number,.answer-reading,.answer-notation,.calendar-date-number").forEach(el=>{const shift=opticalTextShift(el);el.style.translate=`0 ${shift.toFixed(2)}px`})}
function fitShrinkSide(side){if(!side)return;const stack=side.querySelector(".question-stack");if(stack&&!side.classList.contains("wrap-mode-shrink"))stack.style.translate="0 .05em";if(!side.classList.contains("wrap-mode-shrink"))return;const target=side.querySelector(".flash-text,.answer-block,.question-stack,.calendar-date");if(target)fitBlock(side,target,.02)}
function createSide(content,role,displayMode="standard"){const side=document.createElement("div");side.className=`side ${role==="question"?"question-side":"answer-side"}`;const modeEl=role==="question"?$("#qWrapMode"):$("#aWrapMode");const wrapMode=modeEl?modeEl.value:"wrap";side.classList.add(wrapMode==="shrink"?"wrap-mode-shrink":wrapMode==="manual"?"wrap-mode-manual":"wrap-mode-wrap");renderSideContent(side,content,displayMode);return side}
function currentCard(){return cards.length?cards[order[index]]:null}
function semanticValue(card,type){if(card&&card.forms&&card.forms[type]!=null)return card.forms[type];if(type==="visual")return card.left;if(type==="answer")return card.right;return type==="current"?card.left:card.right}
function semanticSides(card){if(!card)return ["",""];if(["hiragana","katakana","romaji"].includes(preset))return [semanticValue(card,builtinQuestionType),semanticValue(card,builtinAnswerType)];return $("#questionPosition").value==="right"?[card.right,card.left]:[card.left,card.right]}
function renderStage(stage,displayMode="standard"){stage.replaceChildren();const c=currentCard();if(!c){const q=createSide("カードがありません","question",displayMode),a=createSide("","answer",displayMode);stage.append(q,a);requestAnimationFrame(()=>{applyOpticalTextCenter(q);applyOpticalTextCenter(a);fitShrinkSide(q);fitShrinkSide(a)});return}const [q,a]=semanticSides(c);const qSide=createSide(q,"question",displayMode),aSide=createSide(a,"answer",displayMode);stage.append(qSide,aSide);requestAnimationFrame(()=>{applyOpticalTextCenter(qSide);applyOpticalTextCenter(aSide);fitShrinkSide(qSide);fitShrinkSide(aSide)})}
function renderTeacher(){const stage=$("#teacherDisplay");stage.classList.toggle("answer-hidden",!teacherAnswerVisible);renderStage(stage,currentTeacherDisplayMode());$("#teacherProgress").textContent=cards.length?`${index+1} / ${cards.length}`:"0 / 0"}
function renderLearner(){const stage=$("#learnerStage");stage.classList.toggle("answer-hidden",!learnerJudged);renderStage(stage,currentLearnerDisplayMode());$("#learnerProgress").textContent=cards.length?`${index+1} / ${cards.length}`:"0 / 0"}
function renderAll(){renderTeacher();renderLearner();updateSwapLabel()}
function presetTypeOptions(){if(preset==="hiragana")return [["hiragana","ひらがな"],["romaji","ローマ字"]];if(preset==="katakana")return [["katakana","カタカナ"],["romaji","ローマ字"],["hiragana","ひらがな"]];if(preset==="romaji")return [["romaji","ローマ字"],["hiragana","ひらがな"]];if(preset==="counters")return [["visual","絵・数字"],["answer","読み・表記"]];if(preset==="time")return [["visual","数字・図"],["answer","読み・表記"]];return []}
function presetTypeLabels(){const opts=presetTypeOptions(),lab=v=>(opts.find(x=>x[0]===v)||[v,v])[1];if(preset==="custom")return customKind==="counter"?["絵・数字","読み・表記"]:[customSourceHeader||"問題",customTargetHeader||"答え"];return [lab(builtinQuestionType),lab(builtinAnswerType)]}
function defaultTypesForPreset(){if(preset==="hiragana")return ["hiragana","romaji"];if(preset==="katakana")return ["katakana","romaji"];if(preset==="romaji")return ["romaji","hiragana"];if(preset==="counters"||preset==="time")return ["visual","answer"];return ["current","current"]}
function fillSelect(el,options,value){el.replaceChildren();options.forEach(([v,label])=>{const o=document.createElement("option");o.value=v;o.textContent=label;el.appendChild(o)});el.value=value}
function refreshQASelects(){if(preset==="custom"&&customTable){const hs=customTable.headers;fillSelect($("#questionTypeSelect"),hs.map(h=>[h,h]),customSourceHeader);fillSelect($("#answerTypeSelect"),hs.map(h=>[h,h]),customTargetHeader);$("#swapState").textContent=`問題：${customSourceHeader} ／ 答え：${customTargetHeader}`;return}const opts=presetTypeOptions();if(preset==="counters"||preset==="time"){const rev=$("#questionPosition").value==="right",q=rev?"answer":"visual",a=rev?"visual":"answer";fillSelect($("#questionTypeSelect"),opts,q);fillSelect($("#answerTypeSelect"),opts,a);const lab=v=>(opts.find(x=>x[0]===v)||["",v])[1];$("#swapState").textContent=`問題：${lab(q)} ／ 答え：${lab(a)}`;return}fillSelect($("#questionTypeSelect"),opts,builtinQuestionType);fillSelect($("#answerTypeSelect"),opts,builtinAnswerType);const labels=presetTypeLabels();$("#swapState").textContent=`問題：${labels[0]} ／ 答え：${labels[1]}`}
function learnerTypeLabel(value,label){const map={hiragana:"Hiragana",katakana:"Katakana",romaji:"Romaji",visual:preset==="time"?"Number / visual":"Picture + number",answer:"Reading + notation"};return map[value]||label}
function learnerOptions(options){return options.map(([v,l])=>[v,learnerTypeLabel(v,l)])}
function refreshLearnerSelectors(){const visual=(preset==="counters"||preset==="time"||(preset==="custom"&&customKind==="counter"));if(preset==="custom"&&customTable){const hs=customTable.headers;fillSelect($("#learnerQuestionTypeSelect"),hs.map(h=>[h,h]),customSourceHeader);fillSelect($("#learnerAnswerTypeSelect"),hs.map(h=>[h,h]),customTargetHeader);$("#learnerDirectionNote").textContent="";$("#learnerOrderSelect").value=shuffle?"shuffle":"ordered";return}const opts=presetTypeOptions();if(visual){const qv=(preset==="counters"||preset==="time")?"visual":builtinQuestionType;const av=(preset==="counters"||preset==="time")?"answer":builtinAnswerType;const lab=v=>(opts.find(x=>x[0]===v)||["",v])[1];fillSelect($("#learnerQuestionTypeSelect"),[[qv,learnerTypeLabel(qv,lab(qv))]],qv);fillSelect($("#learnerAnswerTypeSelect"),[[av,learnerTypeLabel(av,lab(av))]],av)}else{fillSelect($("#learnerQuestionTypeSelect"),learnerOptions(opts),builtinQuestionType);fillSelect($("#learnerAnswerTypeSelect"),learnerOptions(opts),builtinAnswerType)}$("#learnerOrderSelect").value=shuffle?"shuffle":"ordered";$("#learnerDirectionNote").textContent=visual?"この教材では、Learner Modeは「読み・表記」を入力する方向で練習します。":""}
function updateSwapLabel(){refreshQASelects();refreshLearnerSelectors()}
