/* ---------- display settings ---------- */
function applyDisplay(){const root=document.documentElement.style;root.setProperty("--q-font",$("#qFont").value);root.setProperty("--q-size",$("#qSize").value+"px");root.setProperty("--q-weight",$("#qWeight").value);root.setProperty("--q-bg",$("#qBg").value);root.setProperty("--q-text",$("#qText").value);root.setProperty("--a-font",$("#aFont").value);root.setProperty("--a-size",$("#aSize").value+"px");root.setProperty("--a-weight",$("#aWeight").value);root.setProperty("--a-bg",$("#aBg").value);root.setProperty("--a-text",$("#aText").value);$("#qSizeValue").textContent=$("#qSize").value+" px";$("#aSizeValue").textContent=$("#aSize").value+" px";$("#qInlineFontPreview").style.fontFamily=$("#qFont").value;$("#qInlineFontPreview").style.fontWeight=$("#qWeight").value;$("#aInlineFontPreview").style.fontFamily=$("#aFont").value;$("#aInlineFontPreview").style.fontWeight=$("#aWeight").value;renderAll();updateSettingsPreview()}
["qFont","qSize","qWeight","qBg","qText","aFont","aSize","aWeight","aBg","aText","qWrapMode","aWrapMode"].forEach(id=>{const el=$("#"+id);el.addEventListener("input",applyDisplay);el.addEventListener("change",applyDisplay)});
function updateSettingsPreview(){const pq=$("#previewQuestion"),pa=$("#previewAnswer"),qi=$("#previewQuestionInner"),ai=$("#previewAnswerInner"),warn=$("#previewOverflowWarning");if(!pq||!pa||!qi||!ai)return;pq.style.fontFamily=$("#qFont").value;pq.style.fontWeight=$("#qWeight").value;pq.style.color=$("#qText").value;pq.style.background=$("#qBg").value;pa.style.fontFamily=$("#aFont").value;pa.style.fontWeight=$("#aWeight").value;pa.style.color=$("#aText").value;pa.style.background=$("#aBg").value;const visualOverflow=side=>{if(!side)return false;const target=side.querySelector(".flash-text,.answer-block,.question-stack,.calendar-date");if(!target)return false;const sr=side.getBoundingClientRect(),tr=target.getBoundingClientRect(),tol=2;return tr.left<sr.left-tol||tr.right>sr.right+tol||tr.top<sr.top-tol||tr.bottom>sr.bottom+tol};const copyActualToPreview=(preview,inner,actual)=>{if(!actual)return;inner.replaceChildren(...[...actual.childNodes].map(n=>n.cloneNode(true)));const aw=Math.max(1,actual.clientWidth),ah=Math.max(1,actual.clientHeight);const pw=Math.max(1,preview.clientWidth-16),ph=Math.max(1,preview.clientHeight-16);const scale=Math.min(pw/aw,ph/ah);inner.style.width=aw+"px";inner.style.height=ah+"px";inner.style.maxWidth="none";inner.style.maxHeight="none";inner.style.fontSize=getComputedStyle(actual).fontSize;inner.style.transform=`translate(-50%,-50%) scale(${scale})`};requestAnimationFrame(()=>requestAnimationFrame(()=>{const actualQ=$("#teacherDisplay .question-side"),actualA=$("#teacherDisplay .answer-side");copyActualToPreview(pq,qi,actualQ);copyActualToPreview(pa,ai,actualA);const overflowQ=visualOverflow(actualQ),overflowA=visualOverflow(actualA);if(warn){if(overflowQ||overflowA){warn.textContent=`注意：${overflowQ&&overflowA?"問題・答え":overflowQ?"問題":"答え"}は、この設定では実際のカードからはみ出しています。`;warn.classList.add("show")}else warn.classList.remove("show")}}))}
function selectSettingsPanel(which){const q=which==="q";$("#questionSettingsPanel").classList.toggle("settings-selected",q);$("#answerSettingsPanel").classList.toggle("settings-selected",!q);(q?$("#questionSettingsPanel"):$("#answerSettingsPanel")).scrollIntoView({behavior:"smooth",block:"nearest"})}
$("#previewQuestion").onclick=()=>selectSettingsPanel("q");$("#previewAnswer").onclick=()=>selectSettingsPanel("a");
["saveDisplayBtn","resetDisplayBtn"].forEach(id=>$("#"+id)?.addEventListener("click",e=>e.stopPropagation()));
$("#saveDisplayBtn").onclick=()=>{try{localStorage.setItem("a2-display",JSON.stringify({qFont:$("#qFont").value,qSize:$("#qSize").value,qBg:$("#qBg").value,qText:$("#qText").value,aFont:$("#aFont").value,aSize:$("#aSize").value,aBg:$("#aBg").value,aText:$("#aText").value,qWeight:$("#qWeight").value,aWeight:$("#aWeight").value,qWrapMode:$("#qWrapMode").value,aWrapMode:$("#aWrapMode").value}));alert("表示設定を保存しました。")}catch(err){alert("この環境では表示設定を端末内に保存できません。カード機能はそのまま利用できます。")}};
$("#resetDisplayBtn").onclick=()=>{try{localStorage.removeItem("a2-display")}catch(err){}location.reload()};
const localFontWeights=new Map();
function weightFromStyle(style=""){const s=String(style).toLowerCase();if(s.includes("thin"))return 100;if(s.includes("extra light")||s.includes("extralight")||s.includes("ultra light"))return 200;if(s.includes("light"))return 300;if(s.includes("medium"))return 500;if(s.includes("semi bold")||s.includes("semibold")||s.includes("demi bold"))return 600;if(s.includes("extra bold")||s.includes("extrabold")||s.includes("ultra bold"))return 800;if(s.includes("black")||s.includes("heavy"))return 900;if(s.includes("bold"))return 700;return 400}
function setWeightOptions(selectId,fontSelectId){const ws=$("#"+selectId),fs=$("#"+fontSelectId);if(!ws||!fs)return;const family=fs.selectedOptions[0]?.dataset?.family;const vals=family&&localFontWeights.has(family)?[...localFontWeights.get(family)].sort((a,b)=>a-b):[300,400,500,600,700];const current=Number(ws.value)||400;ws.replaceChildren();vals.forEach(v=>{const o=document.createElement("option");o.value=String(v);o.textContent=({100:"Thin",200:"ExtraLight",300:"Light",400:"Regular",500:"Medium",600:"SemiBold",700:"Bold",800:"ExtraBold",900:"Black"})[v]||String(v);ws.appendChild(o)});ws.value=vals.includes(current)?String(current):String(vals.includes(400)?400:vals[0])}
function addFontOption(selectEl,name,cssFamily){if([...selectEl.options].some(o=>o.textContent===name))return;const o=document.createElement("option");o.value=cssFamily;o.textContent=name;o.dataset.family=name;selectEl.appendChild(o)}
function refreshFontPreview(){const p=$("#fontPreview");if(!p)return;p.style.fontFamily=$("#qFont").value}
$("#qFont").addEventListener("change",()=>{refreshFontPreview();applyDisplay()});$("#aFont").addEventListener("change",()=>applyDisplay());
let loadedLocalFontNames=[];
function renderFontGrid(filter=""){const grid=$("#fontGrid");if(!grid)return;const q=filter.trim().toLowerCase();grid.replaceChildren();loadedLocalFontNames.filter(n=>!q||n.toLowerCase().includes(q)).forEach(name=>{const b=document.createElement("button");b.type="button";b.className="font-chip";const useAnswer=$("#answerSettingsPanel").classList.contains("settings-selected");const selectedFamily=(useAnswer?$("#aFont"):$("#qFont")).value;b.classList.toggle("selected-font",selectedFamily===`"${name}"`);b.innerHTML=`<strong>${name}</strong><span>あいうえお 漢字 ABC</span>`;b.querySelector("span").style.fontFamily=`"${name}"`;b.onclick=()=>{const value=`"${name}"`;const useAnswer=$("#answerSettingsPanel").classList.contains("settings-selected");const target=useAnswer?$("#aFont"):$("#qFont");target.value=value;applyDisplay();renderFontGrid($("#fontSearch").value)};grid.appendChild(b)});grid.classList.toggle("hidden",loadedLocalFontNames.length===0)}
$("#fontSearch").addEventListener("input",e=>renderFontGrid(e.target.value));
function localFontPriority(name){const s=String(name).toLowerCase();if(/ud\s*(digi\s*)?kyokasho/.test(s)||/ud.*教科書/.test(s))return 0;if(/kyokasho/.test(s)||/教科書/.test(s))return 1;if(/\bud\b/.test(s)||s.includes("ud"))return 2;return 10}
function promoteUdKyokashoOptions(select,names){const priority=names.filter(n=>localFontPriority(n)===0);if(!priority.length||!select.options.length)return;const frag=document.createDocumentFragment();priority.forEach(name=>{const opt=[...select.options].find(o=>o.textContent===name);if(opt)frag.appendChild(opt)});select.options[0].after(frag)}
$("#loadPcFontsBtn").onclick=async()=>{const status=$("#fontStatus");try{if(!window.queryLocalFonts)throw new Error("このブラウザはPCフォント一覧取得に対応していません。");const fonts=await window.queryLocalFonts();localFontWeights.clear();fonts.forEach(f=>{if(!f.family)return;if(!localFontWeights.has(f.family))localFontWeights.set(f.family,new Set());localFontWeights.get(f.family).add(weightFromStyle(f.style||f.fullName||""))});const names=[...localFontWeights.keys()].sort((a,b)=>localFontPriority(a)-localFontPriority(b)||a.localeCompare(b,"ja"));loadedLocalFontNames=names;names.forEach(name=>{const css=`"${name.replaceAll('"','\\"')}"`;addFontOption($("#qFont"),name,css);addFontOption($("#aFont"),name,css)});promoteUdKyokashoOptions($("#qFont"),names);promoteUdKyokashoOptions($("#aFont"),names);renderFontGrid($("#fontSearch").value);status.textContent=`${names.length}種類のPCフォントを読み込み、問題・答えのフォントメニューに追加しました。`}catch(err){status.textContent=`PCフォント一覧を取得できません：${err.message} 標準フォントを利用してください。`}};
