/* ---------- time / calendar ---------- */
const selectedTimeCats=new Set(["hour","duration","minute","date","month"]);
const hourRead=["","いちじ","にじ","さんじ","よじ","ごじ","ろくじ","しちじ","はちじ","くじ","じゅうじ","じゅういちじ","じゅうにじ"];
const durationRead=["","いちじかん","にじかん","さんじかん","よじかん","ごじかん","ろくじかん",["ななじかん","しちじかん"],"はちじかん","くじかん","じゅうじかん"];
const minuteRead={1:["いっぷん"],2:["にふん"],3:["さんぷん"],4:["よんふん","よんぷん"],5:["ごふん"],6:["ろっぷん"],7:["ななふん"],8:["はちふん","はっぷん"],9:["きゅうふん"],10:["じゅっぷん","じっぷん"]};
const dateRead={1:"ついたち",2:"ふつか",3:"みっか",4:"よっか",5:"いつか",6:"むいか",7:"なのか",8:"ようか",9:"ここのか",10:"とおか",11:"じゅういちにち",12:"じゅうににち",13:"じゅうさんにち",14:"じゅうよっか",15:"じゅうごにち",16:"じゅうろくにち",17:"じゅうしちにち",18:"じゅうはちにち",19:"じゅうくにち",20:"はつか",21:"にじゅういちにち",22:"にじゅうににち",23:"にじゅうさんにち",24:"にじゅうよっか",25:"にじゅうごにち",26:"にじゅうろくにち",27:"にじゅうしちにち",28:"にじゅうはちにち",29:"にじゅうくにち",30:"さんじゅうにち",31:"さんじゅういちにち"};
const monthRead=["","いちがつ","にがつ","さんがつ","しがつ","ごがつ","ろくがつ","しちがつ","はちがつ","くがつ","じゅうがつ","じゅういちがつ","じゅうにがつ"];
function simpleCalendarCard(id,left,reading,notation,variants=[]){return {id,type:"pair",group:"time",left:left,right:{readings:Array.isArray(reading)?reading:[reading],notation:notation},learner:{correct:Array.isArray(reading)?reading:[reading],acceptedVariants:variants}}}
function timeCards(){const out=[];if(selectedTimeCats.has("hour"))for(let n=1;n<=12;n++)out.push(simpleCalendarCard(`hour-${n}`,`${n}:00`,hourRead[n],`${n}時`));if(selectedTimeCats.has("duration"))for(let n=1;n<=10;n++)out.push(simpleCalendarCard(`duration-${n}`,`${n} h`,durationRead[n],`${n}時間`));if(selectedTimeCats.has("minute"))for(let n=1;n<=10;n++)out.push(simpleCalendarCard(`minute-${n}`,`${n} min`,minuteRead[n],`${n}分`));if(selectedTimeCats.has("date"))for(let n=1;n<=31;n++)out.push(simpleCalendarCard(`date-${n}`,{calendarDate:n},dateRead[n],`${n}日`));if(selectedTimeCats.has("month"))for(let n=1;n<=12;n++)out.push(simpleCalendarCard(`month-${n}`,`${n}月`,monthRead[n],`${n}月`));return out}
function updateTimeStatus(){const el=$("#timeStatus");if(el)el.textContent=`選択中：${timeCards().length}枚`}
/* ---------- state ---------- */
let mode="teacher",preset="hiragana",selectedGroups=new Set(["a"]),selectedSpecial=new Set(),selectedCounters=new Set(["sai","nin","tsu","mai","dai"]);
let cards=[],order=[],index=0,shuffle=false,learnerJudged=false,teacherAnswerVisible=false;
let builtinQuestionType="hiragana",builtinAnswerType="romaji";
let customCards=[];let customTable=null;let customSourceHeader=null,customTargetHeader=null,customKind="pair";
/* ---------- range UI ---------- */
function makeRangeButton(id,label,parent,cls=""){const b=document.createElement("button");b.className="range-btn "+cls;b.dataset.group=id;b.textContent=label;b.onclick=()=>{const set=id.startsWith("ks:")?selectedSpecial:selectedGroups;set.has(id)?set.delete(id):set.add(id);syncRangeButtons();updateSelectionStatus();if(preset==="hiragana"||preset==="katakana"||preset==="romaji")resetOrder()};parent.appendChild(b)}
function initRanges(){const basic=$("#basicRange");const pairedRows=[["a",null,null],["ka","ga",null],["sa","za",null],["ta","da",null],["na",null,null],["ha","ba","pa"],["ma",null,null],["ya",null,null],["ra",null,null],["wa",null,null]];pairedRows.forEach(row=>{const family=document.createElement("div");family.className="range-family";row.filter(Boolean).forEach(id=>makeRangeButton(id,groupLabels[id],family,(daku.includes(id)||handaku.includes(id))?"compact":""));basic.appendChild(family)});const youonRows=[["kya","gya",null],["sha","ja",null],["cha",null,null],["nya",null,null],["hya","bya","pya"],["mya",null,null],["rya",null,null]];const youonBox=$("#youonRange");youonRows.forEach(row=>{const family=document.createElement("div");family.className="range-family";row.filter(Boolean).forEach(id=>makeRangeButton(id,groupLabels[id],family,(id==="gya"||id==="ja"||id==="bya"||id==="pya")?"compact":""));youonBox.appendChild(family)});specialMora.forEach(id=>makeRangeButton(id,groupLabels[id],$("#specialMoraRange")));kataSpecial.forEach(([k,r],i)=>makeRangeButton("ks:"+i,k,$("#katakanaSpecialRange"),"compact"));Object.entries(counterDefs).forEach(([id,d])=>{const b=document.createElement("button");b.className="counter-btn";b.dataset.counter=id;b.textContent=d.label;b.onclick=()=>{const next=new Set(selectedCounters);next.has(id)?next.delete(id):next.add(id);if(preset==="counters"){const test=validateCardSet(counterCards([...next],$("#includeQuestionCard").checked),{checkQuestionCollisions:true});if(test.errors.length){const first=test.errors[0].message;const suffix=test.errors.length>1?`（同様の競合 ${test.errors.length}件）`:"";setRuntimeStatus([first+suffix],"error");return}}selectedCounters=next;syncCounterButtons();updateCounterStatus();if(preset==="counters")resetOrder()};(d.kind==="basic"?$("#counterBasic"):$("#counterExtra")).appendChild(b)});syncRangeButtons();syncCounterButtons();updateSelectionStatus();updateCounterStatus()}
function syncRangeButtons(){$$(".range-btn[data-group]").forEach(b=>{const set=b.dataset.group.startsWith("ks:")?selectedSpecial:selectedGroups;b.classList.toggle("selected",set.has(b.dataset.group))})}
function syncCounterButtons(){$$(".counter-btn").forEach(b=>b.classList.toggle("selected",selectedCounters.has(b.dataset.counter)))}
function updateSelectionStatus(){const n=buildKanaCards(false).length;$("#selectionStatus").textContent=`選択中：${n}枚`}
function updateCounterStatus(){const n=counterCards([...selectedCounters],$("#includeQuestionCard").checked).length;$("#counterStatus").textContent=`選択中：${n}枚`}
$$("[data-bulk]").forEach?.(()=>{});
document.addEventListener("click",e=>{const k=(e.target&&e.target.dataset)?e.target.dataset.bulk:null;if(!k)return;if(k==="clear")selectedGroups.clear();if(k==="seion")seion.forEach(x=>selectedGroups.add(x));if(k==="daku")daku.forEach(x=>selectedGroups.add(x));if(k==="handaku")handaku.forEach(x=>selectedGroups.add(x));if(k==="basicAll")baseOrder.forEach(x=>selectedGroups.add(x));if(k==="youonAll")youon.forEach(x=>selectedGroups.add(x));if(k==="youonClear")youon.forEach(x=>selectedGroups.delete(x));if(k==="specialAll")kataSpecial.forEach((_,i)=>selectedSpecial.add("ks:"+i));if(k==="specialClear")selectedSpecial.clear();syncRangeButtons();updateSelectionStatus();if(preset==="hiragana"||preset==="katakana"||preset==="romaji")resetOrder()});
