/* ---------- navigation/order ---------- */
function go(delta){if(!cards.length)return;index=(index+delta+cards.length)%cards.length;learnerJudged=false;teacherAnswerVisible=false;$("#learnerInput").value="";$("#feedback").textContent="Enter your answer and press Check.";$("#feedback").className="feedback";renderAll()}
function teacherNext(){if(!cards.length)return;if(!teacherAnswerVisible){teacherAnswerVisible=true;renderTeacher();return}go(1)}
function teacherPrev(){if(!cards.length)return;go(-1)}
$("#prevBtn").onclick=teacherPrev;$("#nextBtn").onclick=teacherNext;$("#learnerNextBtn").onclick=()=>go(1);
function syncOrderButtons(){$("#orderModeSelect").value=shuffle?"shuffle":"ordered";["orderedBtn","orderedBtnStage","orderedBtnLearner"].forEach(id=>$("#"+id)?.classList.toggle("active",!shuffle));["shuffleBtn","shuffleBtnStage","shuffleBtnLearner"].forEach(id=>$("#"+id)?.classList.toggle("active",shuffle))}
function setShuffleMode(value){shuffle=!!value;syncOrderButtons();resetOrder()}
["orderedBtn","orderedBtnStage","orderedBtnLearner"].forEach(id=>{const el=$("#"+id);if(el)el.onclick=()=>setShuffleMode(false)});
["shuffleBtn","shuffleBtnStage","shuffleBtnLearner"].forEach(id=>{const el=$("#"+id);if(el)el.onclick=()=>setShuffleMode(true)});
$("#swapBtn").onclick=()=>{if(preset==="custom"&&customTable){[customSourceHeader,customTargetHeader]=[customTargetHeader,customSourceHeader];resetOrder();updateSwapLabel();return}if(["hiragana","katakana","romaji"].includes(preset)){[builtinQuestionType,builtinAnswerType]=[builtinAnswerType,builtinQuestionType];resetOrder();updateSwapLabel();return}$("#questionPosition").value=$("#questionPosition").value==="left"?"right":"left";renderAll();updateSwapLabel()};
$("#questionPosition").onchange=()=>{renderAll();updateSwapLabel()};
$("#questionTypeSelect").onchange=()=>{if(preset==="custom"&&customTable){customSourceHeader=$("#questionTypeSelect").value;if(customSourceHeader===customTargetHeader)customTargetHeader=customTable.headers.find(h=>h!==customSourceHeader)||customTargetHeader;resetOrder();updateSwapLabel();return}if(preset==="counters"||preset==="time"){$("#questionPosition").value=$("#questionTypeSelect").value==="answer"?"right":"left";renderAll();updateSwapLabel();return}const v=$("#questionTypeSelect").value;if(v===builtinAnswerType){const alt=presetTypeOptions().find(x=>x[0]!==v)?.[0];if(alt)builtinAnswerType=alt}builtinQuestionType=v;$("#questionPosition").value="left";resetOrder();updateSwapLabel()};
$("#answerTypeSelect").onchange=()=>{if(preset==="custom"&&customTable){customTargetHeader=$("#answerTypeSelect").value;if(customTargetHeader===customSourceHeader)customSourceHeader=customTable.headers.find(h=>h!==customTargetHeader)||customSourceHeader;resetOrder();updateSwapLabel();return}if(preset==="counters"||preset==="time"){$("#questionPosition").value=$("#answerTypeSelect").value==="visual"?"right":"left";renderAll();updateSwapLabel();return}const v=$("#answerTypeSelect").value;if(v===builtinQuestionType){const alt=presetTypeOptions().find(x=>x[0]!==v)?.[0];if(alt)builtinQuestionType=alt}builtinAnswerType=v;$("#questionPosition").value="left";resetOrder();updateSwapLabel()};
$("#orderModeSelect").onchange=()=>setShuffleMode($("#orderModeSelect").value==="shuffle");
$("#scriptMode").onchange=()=>{renderAll();updateSettingsPreview()};
$("#learnerScript").onchange=()=>renderLearner();
/* ---------- preset switch ---------- */
$("#presetTabs").addEventListener("click",e=>{const p=e.target.dataset.preset;if(!p)return;preset=p;[builtinQuestionType,builtinAnswerType]=defaultTypesForPreset();$("#questionPosition").value="left";updateSwapLabel();refreshDisplayModeSelects();$$("#presetTabs button").forEach(b=>b.classList.toggle("active",b.dataset.preset===p));$("#kanaChooser").classList.toggle("hidden",p==="counters"||p==="time"||p==="custom");$("#counterChooser").classList.toggle("hidden",p!=="counters");$("#timeChooser").classList.toggle("hidden",p!=="time");$("#katakanaSpecialDetails").classList.toggle("hidden",p!=="katakana");if(p==="custom"&&!customCards.length){const d=$("#importDetails");if(d)d.open=true;setRuntimeStatus(["下の「カードセットを読み込む／保存する」から自作セットを読み込んでください。"],"warn")}resetOrder()});
$("#includeQuestionCard").onchange=()=>{const prev=!$("#includeQuestionCard").checked;if(preset==="counters"){const test=validateCardSet(counterCards([...selectedCounters],$("#includeQuestionCard").checked),{checkQuestionCollisions:true});if(test.errors.length){$("#includeQuestionCard").checked=prev;const first=test.errors[0].message;const suffix=test.errors.length>1?`（同様の競合 ${test.errors.length}件）`:"";setRuntimeStatus([first+suffix],"error")}}updateCounterStatus();if(preset==="counters")resetOrder()};
$("#timeCategories").addEventListener("click",e=>{const id=(e.target&&e.target.dataset)?e.target.dataset.timecat:null;if(!id)return;selectedTimeCats.has(id)?selectedTimeCats.delete(id):selectedTimeCats.add(id);e.target.classList.toggle("selected",selectedTimeCats.has(id));updateTimeStatus();if(preset==="time")resetOrder()});
