/* ---------- fullscreen ---------- */
function clearFullscreenSelection(){try{document.activeElement?.blur?.()}catch{}try{window.getSelection?.()?.removeAllRanges?.()}catch{}}
$("#fullscreenBtn").onclick=async e=>{e.preventDefault();e.stopPropagation();clearFullscreenSelection();document.body.classList.add("fullscreen");try{await document.documentElement.requestFullscreen?.()}catch{};clearFullscreenSelection()};
$("#fullscreenExit").onclick=async e=>{e.preventDefault();e.stopPropagation();document.body.classList.remove("fullscreen");clearFullscreenSelection();try{await document.exitFullscreen?.()}catch{}};
document.addEventListener("fullscreenchange",()=>{if(!document.fullscreenElement)document.body.classList.remove("fullscreen");clearFullscreenSelection()});
$("#teacherPanel").addEventListener("mousedown",e=>{if(document.body.classList.contains("fullscreen"))e.preventDefault()});
$("#teacherPanel").addEventListener("click",e=>{if(document.body.classList.contains("fullscreen")){e.preventDefault();e.stopPropagation();clearFullscreenSelection();teacherNext()}});
document.addEventListener("keydown",e=>{if(!document.body.classList.contains("fullscreen"))return;if(e.key===" "||e.key==="ArrowRight"||e.key==="Enter"){e.preventDefault();e.stopPropagation();clearFullscreenSelection();teacherNext();clearFullscreenSelection()}else if(e.key==="ArrowLeft"){e.preventDefault();e.stopPropagation();clearFullscreenSelection();teacherPrev()}else if(e.key==="Escape"){e.preventDefault();$("#fullscreenExit").click()}},true);
/* ---------- card validation ---------- */
function canonicalAnswerList(card){return [...(card.learner?.correct||[]),...(card.learner?.acceptedVariants||[])].map(normalizeAnswer).sort()}
function questionSignature(card){const q=card.left;if(q&&typeof q==="object")return JSON.stringify({type:card.type||"object",icons:q.icons||null,image:q.imageName||null,number:q.number??null,calendarDate:q.calendarDate??null});return JSON.stringify({type:card.type||"pair",text:String(q??"")})}
function validateCard(card){const errors=[],warnings=[];const add=(code,message)=>errors.push({code,cardId:card?.id||"(no id)",message:`${card?.id||"(no id)"}: ${message}`});if(!card||typeof card!=="object"){add("INVALID_CARD","カード定義がオブジェクトではありません。");return {errors,warnings}}if(!card.id)add("MISSING_ID","id がありません。");if(card.left===undefined||card.right===undefined)add("MISSING_SIDE","問題／答えのデータが必要です。");const c=card.learner?.correct,v=card.learner?.acceptedVariants??[];if(!Array.isArray(c)||c.length===0)add("EMPTY_CORRECT","correct は1件以上必要です。");if(!Array.isArray(v))add("INVALID_VARIANTS","acceptedVariants は配列で指定してください。");if(Array.isArray(c)&&Array.isArray(v)){const raw=[...c,...v];raw.forEach(x=>{if(typeof x!=="string"||normalizeAnswer(x)==="")add("EMPTY_ANSWER","空の正答候補があります。")});if(new Set(c).size!==c.length)add("DUPLICATE_CORRECT","correct 内に重複があります。");if(new Set(v).size!==v.length)add("DUPLICATE_VARIANT","acceptedVariants 内に重複があります。");if(c.some(x=>v.includes(x)))add("CORRECT_VARIANT_DUPLICATE","correct と acceptedVariants に同じ値があります。");const norm=raw.map(normalizeAnswer);if(new Set(norm).size!==norm.length)add("NORMALIZED_DUPLICATE","正規化後に同一になる正答候補があります。")}return {errors,warnings}}
function validateCardSet(inputCards,{checkQuestionCollisions=false}={}){const errors=[],warnings=[],ids=new Map(),qs=new Map();inputCards.forEach((card,i)=>{const v=validateCard(card);errors.push(...v.errors);warnings.push(...v.warnings);if(card?.id){if(ids.has(card.id))errors.push({code:"DUPLICATE_ID",message:`カードID「${card.id}」が重複しています。`});else ids.set(card.id,i)}if(checkQuestionCollisions&&card){const sig=questionSignature(card),answers=canonicalAnswerList(card).join("\u0001");if(!qs.has(sig))qs.set(sig,{id:card.id,answers});else{const prev=qs.get(sig);errors.push({code:prev.answers===answers?"DUPLICATE_CARD":"AMBIGUOUS_QUESTION",message:prev.answers===answers?`同じ問題「${card.id} / ${prev.id}」が重複しています。`:`同じ問題表示に異なる正答があります（${prev.id} / ${card.id}）。この組み合わせは答えが一意にならないため、どちらか一方のセットを選んでください。`})}}});return {errors,warnings}}
function validateBuiltIns(){const errors=[];const savedGroups=new Set(selectedGroups),savedSpecial=new Set(selectedSpecial);try{Object.keys(groups).forEach(g=>{selectedGroups=new Set([g]);selectedSpecial=new Set();errors.push(...validateCardSet(buildKanaCards(false)).errors)});kataSpecial.forEach((_,i)=>{selectedGroups=new Set();selectedSpecial=new Set([`ks:${i}`]);errors.push(...validateCardSet(buildKanaCards(true)).errors)});Object.keys(counterDefs).forEach(id=>errors.push(...validateCardSet(counterCards([id],true),{checkQuestionCollisions:true}).errors));errors.push(...validateCardSet(timeCards(),{checkQuestionCollisions:true}).errors)}finally{selectedGroups=savedGroups;selectedSpecial=savedSpecial}return errors}
