/* ---------- learner mode ---------- */
function setMode(m){mode=m;const learner=m==="learner";$("#teacherModeBtn").classList.toggle("active",!learner);$("#learnerModeBtn").classList.toggle("active",learner);$("#teacherControls").classList.toggle("hidden",learner);$("#presetPanel").classList.toggle("hidden",learner);$("#teacherPanel").classList.toggle("hidden",learner);$("#teacherNav").classList.toggle("hidden",learner);$("#learnerControls").classList.toggle("hidden",!learner);$("#learnerArea").classList.toggle("hidden",!learner);if(learner){if(currentCard()&&answerIsVisual(currentCard())){$("#questionPosition").value="left";updateSwapLabel()}refreshDisplayModeSelects();learnerJudged=false;renderLearner();setTimeout(()=>$("#learnerInput").focus(),0)}}
$("#teacherModeBtn").onclick=()=>setMode("teacher");$("#learnerModeBtn").onclick=()=>setMode("learner");
$("#learnerQuestionTypeSelect").onchange=()=>{if(preset==="custom"&&customTable){customSourceHeader=$("#learnerQuestionTypeSelect").value;if(customSourceHeader===customTargetHeader)customTargetHeader=customTable.headers.find(h=>h!==customSourceHeader)||customTargetHeader;resetOrder();updateSwapLabel();return}builtinQuestionType=$("#learnerQuestionTypeSelect").value;if(builtinQuestionType===builtinAnswerType){const alt=presetTypeOptions().find(x=>x[0]!==builtinQuestionType)?.[0];if(alt)builtinAnswerType=alt}resetOrder();updateSwapLabel()};
$("#learnerAnswerTypeSelect").onchange=()=>{if(preset==="custom"&&customTable){customTargetHeader=$("#learnerAnswerTypeSelect").value;if(customTargetHeader===customSourceHeader)customSourceHeader=customTable.headers.find(h=>h!==customTargetHeader)||customSourceHeader;resetOrder();updateSwapLabel();return}builtinAnswerType=$("#learnerAnswerTypeSelect").value;if(builtinAnswerType===builtinQuestionType){const alt=presetTypeOptions().find(x=>x[0]!==builtinAnswerType)?.[0];if(alt)builtinQuestionType=alt}resetOrder();updateSwapLabel()};
$("#learnerOrderSelect").onchange=()=>{setShuffleMode($("#learnerOrderSelect").value==="shuffle");refreshLearnerSelectors()};
$("#learnerStartBtn").onclick=()=>{resetOrder();learnerJudged=false;$("#learnerInput").value="";$("#feedback").textContent="Enter your answer and press Check.";$("#feedback").className="feedback";renderLearner();$("#learnerInput").focus()};
function answerIsVisual(c){const [,a]=semanticSides(c);return !!(a&&typeof a==="object"&&(a.icons||a.imageSrc||a.calendarDate))}
function accepted(c){if(["hiragana","katakana","romaji"].includes(preset)){const a=semanticValue(c,builtinAnswerType);return typeof a==="string"?uniq(pairAnswerCandidates(a).map(normalizeAnswer)):[]}const reversed=$("#questionPosition").value==="right";if(!reversed){const l=c?.learner||{};return uniq([...(l.correct||[]),...(l.acceptedVariants||[])].map(normalizeAnswer))}if(c?.left!=null&&typeof c.left!=="object")return[normalizeAnswer(c.left)];return[]}
function displayedAnswerReadings(c){const [,a]=semanticSides(c);if(a&&typeof a==="object"&&a.readings)return a.readings;if(typeof a==="string")return[a];return[]}
function checkLearner(){const c=currentCard(),v=normalizeAnswer($("#learnerInput").value);if(answerIsVisual(c)){$("#feedback").textContent="This direction cannot be answered by typing. Swap Question and Answer.";$("#feedback").className="feedback ng";return}if(!v){$("#feedback").textContent="Type your answer.";$("#feedback").className="feedback ng";return}const ok=accepted(c).includes(v);learnerJudged=true;const shown=displayedAnswerReadings(c);$("#feedback").textContent=ok?"✓ Correct":`✗ Answer: ${shown.join(" / ")}`;$("#feedback").className="feedback "+(ok?"ok":"ng");renderLearner()}
$("#checkBtn").onclick=checkLearner;
$("#showAnswerBtn").onclick=()=>{learnerJudged=true;const c=currentCard(),shown=displayedAnswerReadings(c);$("#feedback").textContent=shown.length?`Answer: ${shown.join(" / ")}`:"Answer shown.";$("#feedback").className="feedback";renderLearner()};
$("#learnerInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();learnerJudged?go(1):checkLearner()}});
