"use strict";

/* ---------- utilities ---------- */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uniq=a=>[...new Set(a)];
function hiraToKata(s){return s.replace(/[\u3041-\u3096]/g,c=>String.fromCharCode(c.charCodeAt(0)+0x60))}
function kataToHira(s){return s.replace(/[\u30A1-\u30F6]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60))}
function normalizeAnswer(s){return kataToHira(String(s??"").normalize("NFKC").trim().replace(/[\s\u3000]+/g,""))}
function csvEscape(s){s=String(s??"");return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function downloadText(name,text,type="text/plain;charset=utf-8"){const b=new Blob([text],{type});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function fitBlock(panel,block,min=.02){if(!panel||!block)return;panel.style.position="relative";block.style.position="absolute";block.style.left="50%";block.style.top="50%";block.style.margin="0";block.style.transformOrigin="center center";block.style.transform="translate(-50%,-50%) scale(1)";const ps=getComputedStyle(panel);const aw=Math.max(1,panel.clientWidth-parseFloat(ps.paddingLeft)-parseFloat(ps.paddingRight));const ah=Math.max(1,panel.clientHeight-parseFloat(ps.paddingTop)-parseFloat(ps.paddingBottom));const nw=Math.max(1,block.scrollWidth||0,block.getBoundingClientRect().width||0);const nh=Math.max(1,block.scrollHeight||0,block.getBoundingClientRect().height||0);const scale=Math.min(1,aw/nw,ah/nh);let optical="";if(block.classList.contains("question-stack"))optical=" translateY(.05em)";else if(block.classList.contains("flash-text"))optical=` translateY(${opticalTextShift(block).toFixed(2)}px)`;block.style.translate="";block.style.transform=`translate(-50%,-50%) scale(${Math.max(min,scale)})${optical}`}

/* ---------- kana data ---------- */
const groups={a:[["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"]],ka:[["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"]],ga:[["が","ga"],["ぎ","gi"],["ぐ","gu"],["げ","ge"],["ご","go"]],sa:[["さ","sa"],["し","shi"],["す","su"],["せ","se"],["そ","so"]],za:[["ざ","za"],["じ","ji"],["ず","zu"],["ぜ","ze"],["ぞ","zo"]],ta:[["た","ta"],["ち","chi"],["つ","tsu"],["て","te"],["と","to"]],da:[["だ","da"],["ぢ","ji"],["づ","zu"],["で","de"],["ど","do"]],na:[["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"]],ha:[["は","ha"],["ひ","hi"],["ふ","fu"],["へ","he"],["ほ","ho"]],ba:[["ば","ba"],["び","bi"],["ぶ","bu"],["べ","be"],["ぼ","bo"]],pa:[["ぱ","pa"],["ぴ","pi"],["ぷ","pu"],["ぺ","pe"],["ぽ","po"]],ma:[["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"]],ya:[["や","ya"],["ゆ","yu"],["よ","yo"]],ra:[["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"]],wa:[["わ","wa"],["を","o / wo"]],N:[["ん","/N/"]],Q:[["っ","/Q/"]],kya:[["きゃ","kya"],["きゅ","kyu"],["きょ","kyo"]],sha:[["しゃ","sha"],["しゅ","shu"],["しょ","sho"]],cha:[["ちゃ","cha"],["ちゅ","chu"],["ちょ","cho"]],nya:[["にゃ","nya"],["にゅ","nyu"],["にょ","nyo"]],hya:[["ひゃ","hya"],["ひゅ","hyu"],["ひょ","hyo"]],mya:[["みゃ","mya"],["みゅ","myu"],["みょ","myo"]],rya:[["りゃ","rya"],["りゅ","ryu"],["りょ","ryo"]],gya:[["ぎゃ","gya"],["ぎゅ","gyu"],["ぎょ","gyo"]],ja:[["じゃ","ja"],["じゅ","ju"],["じょ","jo"]],bya:[["びゃ","bya"],["びゅ","byu"],["びょ","byo"]],pya:[["ぴゃ","pya"],["ぴゅ","pyu"],["ぴょ","pyo"]]};
const groupLabels={a:"あ行",ka:"か行",ga:"が行",sa:"さ行",za:"ざ行",ta:"た行",da:"だ行",na:"な行",ha:"は行",ba:"ば行",pa:"ぱ行",ma:"ま行",ya:"や行",ra:"ら行",wa:"わ行",N:"ん /N/",Q:"っ /Q/",kya:"きゃ",sha:"しゃ",cha:"ちゃ",nya:"にゃ",hya:"ひゃ",mya:"みゃ",rya:"りゃ",gya:"ぎゃ",ja:"じゃ",bya:"びゃ",pya:"ぴゃ"};
const baseOrder=["a","ka","ga","sa","za","ta","da","na","ha","ba","pa","ma","ya","ra","wa"];
const seion=["a","ka","sa","ta","na","ha","ma","ya","ra","wa"], daku=["ga","za","da","ba"], handaku=["pa"];
const youon=["kya","sha","cha","nya","hya","mya","rya","gya","ja","bya","pya"];
const specialMora=["N","Q"];
const kataSpecial=[["ヴァ","va"],["ヴィ","vi"],["ヴ","vu"],["ヴェ","ve"],["ヴォ","vo"],["ヴュ","vyu"],["イェ","ye"],["ウィ","wi"],["ウェ","we"],["ウォ","wo"],["クァ","kwa"],["クィ","kwi"],["クェ","kwe"],["クォ","kwo"],["グァ","gwa"],["グィ","gwi"],["グェ","gwe"],["グォ","gwo"],["スィ","si"],["ズィ","zi"],["シェ","she"],["ジェ","je"],["チェ","che"],["ティ","ti"],["ディ","di"],["トゥ","tu"],["ドゥ","du"],["テュ","tyu"],["デュ","dyu"],["ツァ","tsa"],["ツィ","tsi"],["ツェ","tse"],["ツォ","tso"],["ファ","fa"],["フィ","fi"],["フェ","fe"],["フォ","fo"],["フュ","fyu"],["キェ","kye"],["ギェ","gye"],["ニェ","nye"],["ヒェ","hye"],["ビェ","bye"],["ピェ","pye"],["ミェ","mye"],["リェ","rye"]];

/* ---------- counters ---------- */
const counterDefs={sai:{label:"歳",kind:"basic",icons:["🎂"],max:20,q:"何歳",qreading:["なんさい"]},nin:{label:"人",kind:"basic",icons:["👤"],max:10,q:"何人",qreading:["なんにん"]},tsu:{label:"〜つ",kind:"basic",icons:["🎁","🧸","⚽"],max:10,q:"いくつ",qreading:["いくつ"]},mai:{label:"枚",kind:"basic",icons:["📄","👕"],max:10,q:"何枚",qreading:["なんまい"]},dai:{label:"台",kind:"basic",icons:["🚗","💻"],max:10,q:"何台",qreading:["なんだい"]},ko:{label:"個",kind:"extra",icons:["🍎","🍊","🥚"],max:10,q:"何個",qreading:["なんこ"],qvariants:["なん個"]},hon:{label:"本",kind:"extra",icons:["✏️","☂️"],max:10,q:"何本",qreading:["なんぼん"]},satsu:{label:"冊",kind:"extra",icons:["📕","📓"],max:10,q:"何冊",qreading:["なんさつ"],qvariants:["なん冊"]},hai:{label:"杯",kind:"extra",icons:["☕","🍵"],max:10,q:"何杯",qreading:["なんばい"]}};
const tsuRead=["","ひとつ","ふたつ","みっつ","よっつ","いつつ","むっつ","ななつ","やっつ","ここのつ","とお"];
const ninRead=["","ひとり","ふたり","さんにん","よにん","ごにん","ろくにん",["ななにん","しちにん"],"はちにん","きゅうにん","じゅうにん"];
const regularNum=["","いち","に","さん","よん","ご","ろく","なな","はち","きゅう","じゅう"];
function readingsForCounter(id,n){if(id==="tsu")return[tsuRead[n]];if(id==="nin")return Array.isArray(ninRead[n])?ninRead[n]:[ninRead[n]];if(id==="mai")return[regularNum[n]+"まい"];if(id==="dai")return[regularNum[n]+"だい"];if(id==="ko"){const m={1:"いっこ",2:"にこ",3:"さんこ",4:"よんこ",5:"ごこ",6:"ろっこ",7:"ななこ",8:"はっこ",9:"きゅうこ",10:"じゅっこ"};return n===10?["じゅっこ","じっこ"]:[m[n]]}if(id==="hon"){const m={1:"いっぽん",2:"にほん",3:"さんぼん",4:"よんほん",5:"ごほん",6:"ろっぽん",7:"ななほん",8:"はっぽん",9:"きゅうほん",10:"じゅっぽん"};return n===10?["じゅっぽん","じっぽん"]:[m[n]]}if(id==="satsu"){const m={1:"いっさつ",2:"にさつ",3:"さんさつ",4:"よんさつ",5:"ごさつ",6:"ろくさつ",7:"ななさつ",8:"はっさつ",9:"きゅうさつ",10:"じゅっさつ"};return n===10?["じゅっさつ","じっさつ"]:[m[n]]}if(id==="hai"){const m={1:"いっぱい",2:"にはい",3:"さんばい",4:"よんはい",5:"ごはい",6:"ろっぱい",7:"ななはい",8:"はっぱい",9:"きゅうはい",10:"じゅっぱい"};return n===10?["じゅっぱい","じっぱい"]:[m[n]]}if(id==="sai"){if(n===20)return["はたち"];const m={1:"いっさい",2:"にさい",3:"さんさい",4:"よんさい",5:"ごさい",6:"ろくさい",7:"ななさい",8:"はっさい",9:"きゅうさい",10:"じゅっさい"};if(n<=10)return n===10?["じゅっさい","じっさい"]:[m[n]];const tail={1:"いっさい",2:"にさい",3:"さんさい",4:"よんさい",5:"ごさい",6:"ろくさい",7:"ななさい",8:"はっさい",9:"きゅうさい"};return["じゅう"+tail[n-10]]}return[String(n)]}
function variantsForCounter(id,n,reads){const out=[];if(id==="ko")reads.forEach(r=>out.push(r.replace(/こ$/,"個")));if(id==="mai")reads.forEach(r=>out.push(r.replace(/まい$/,"枚")));if(id==="dai")reads.forEach(r=>out.push(r.replace(/だい$/,"台")));if(id==="satsu")reads.forEach(r=>out.push(r.replace(/さつ$/,"冊")));return uniq(out.filter(v=>!reads.includes(v)))}
function counterCards(ids,includeQ){const cards=[];ids.forEach(id=>{const d=counterDefs[id];for(let n=1;n<=d.max;n++){const rs=readingsForCounter(id,n);cards.push({id:`${id}-${n}`,type:"counter",group:id,counter:d.label.replace("〜",""),left:{icons:d.icons,number:String(n)},right:{readings:rs,notation:(id==="tsu"&&n===10)?"10":`${n}${d.label.replace("〜","")}`},learner:{correct:rs,acceptedVariants:variantsForCounter(id,n,rs)}})}if(includeQ)cards.push({id:`${id}-q`,type:"counter",group:id,counter:d.label.replace("〜",""),left:{icons:d.icons,number:"？"},right:{readings:d.qreading,notation:d.q},learner:{correct:d.qreading,acceptedVariants:d.qvariants||[]}})});return cards}
