/* ---------- card builders ---------- */
function pairAnswerCandidates(value){const parts=String(value).split(/\s*\/\s*/).map(x=>x.trim()).filter(Boolean);return parts.length>1?parts:[String(value)]}
function buildKanaCards(useKata){const out=[];const ordered=[...baseOrder,...youon,...specialMora];ordered.forEach(g=>{if(!selectedGroups.has(g))return;(groups[g]||[]).forEach(([h,r],i)=>{const char=useKata?hiraToKata(h):h;out.push({id:`${useKata?"kata":"hira"}-${g}-${i}`,type:"pair",group:g,left:char,right:r,forms:{hiragana:h,katakana:hiraToKata(h),romaji:r},learner:{correct:pairAnswerCandidates(r),acceptedVariants:[]}})})});if(useKata)[...selectedSpecial].sort((a,b)=>+a.split(":")[1]-+b.split(":")[1]).forEach(id=>{const [k,r]=kataSpecial[+id.split(":")[1]];out.push({id:`kata-${id}`,type:"pair",group:"special",left:k,right:r,forms:{hiragana:kataToHira(k),katakana:k,romaji:r},learner:{correct:pairAnswerCandidates(r),acceptedVariants:[]}})});return out}
function buildCustomCards(){if(!customTable)return customCards.slice();return customTable.rows.map((r,i)=>{const left=r.values[customSourceHeader]??"",right=r.values[customTargetHeader]??"";const useMeta=customTargetHeader===customTable.defaultTarget;return {id:`custom-${i+1}`,type:"pair",left,right,learner:{correct:useMeta&&r.correct.length?r.correct:[right],acceptedVariants:useMeta?r.acceptedVariants:[]}}})}
function presetLabel(){return ({hiragana:"ひらがな",katakana:"カタカナ",romaji:"ローマ字",counters:"数え方",time:"時間・暦",custom:"自作セット"})[preset]||"カード"}
function buildPreset(){if(preset==="hiragana")return buildKanaCards(false);if(preset==="katakana")return buildKanaCards(true);if(preset==="romaji")return buildKanaCards(false).map(c=>({...c,left:c.right,right:c.left,learner:{correct:[c.left],acceptedVariants:[]}}));if(preset==="counters")return counterCards([...selectedCounters],$("#includeQuestionCard").checked);if(preset==="time")return timeCards();if(preset==="custom")return buildCustomCards();return []}
function setRuntimeStatus(messages=[],severity="error"){const el=$("#runtimeStatus");if(!messages.length){el.className="status hidden";el.textContent="";return}el.className=`status ${severity}`;el.innerHTML=messages.map(x=>`<div>${escapeHtml(x)}</div>`).join("")}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function resetOrder(){const nextCards=buildPreset();if(!nextCards.length){cards=[];order=[];index=0;teacherAnswerVisible=false;learnerJudged=false;$("#cardCount").value=0;if($("#cardCountText"))$("#cardCountText").textContent="0枚";setRuntimeStatus(["出題する項目を1つ以上選択してください。"],"warn");renderAll();return true}const validation=validateCardSet(nextCards,{checkQuestionCollisions:true});if(validation.errors.length){setRuntimeStatus(validation.errors.map(e=>e.message),"error");return false}setRuntimeStatus(validation.warnings.map(e=>e.message),validation.warnings.length?"warn":"ok");cards=nextCards;order=cards.map((_,i)=>i);if(shuffle)shuffleArray(order);index=0;teacherAnswerVisible=false;$("#cardCount").value=cards.length;if($("#cardCountText"))$("#cardCountText").textContent=cards.length+"枚";if($("#setStatus"))$("#setStatus").textContent=`${presetLabel()} ${cards.length}項目`;renderAll();updateSwapLabel();updateSettingsPreview();return true}
function shuffleArray(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
